import type { ColorThemePreset } from "@/lib/color-themes";

export const GENERAL_SETTINGS_LIMITS = {
  cornerRadius: { min: 0, max: 40, step: 1 },
  tileSpacing: { min: 0.15, max: 2.5, step: 0.05 },
  dividerSpacing: { min: 10, max: 40, step: 1 },
  dividerWidth: { min: 1, max: 10, step: 1 },
  dividerBackgroundSize: { min: 2, max: 18, step: 1 },
  mathFontSize: { min: 0.8, max: 2.5, step: 0.05 },
  mathInlineVerticalAlign: { min: -0.8, max: 0.3, step: 0.01 },
  mathInlineTranslateY: { min: -0.8, max: 0.8, step: 0.01 },
  imageUploadLimitMb: { min: 1, max: 250, step: 1 },
  fileUploadLimitMb: { min: 5, max: 1024, step: 5 },
  appSidebarWidth: { min: 220, max: 360, step: 4 },
  appInspectorWidth: { min: 260, max: 480, step: 4 },
  publicLeftPanelWidth: { min: 220, max: 460, step: 4 },
  publicRightPanelWidth: { min: 220, max: 460, step: 4 },
} as const;

export const DEFAULT_GENERAL_SETTINGS = {
  colorTheme: "paper" as ColorThemePreset,
  cornerRadius: 0,
  tileSpacing: 0.75,
  dividerSpacing: 10,
  dividerColor: "#7c6650",
  dividerWidth: 2,
  dividerBackgroundSize: 12,
  collapseBookChaptersByDefault: true,
  mathFontSize: 1,
  mathFontColor: "#000077",
  mathFontFamily: "mathjax-newcm",
  mathInlineVerticalAlign: 0,
  mathInlineTranslateY: 0.2,
  imageUploadLimitMb: 10,
  fileUploadLimitMb: 50,
  appSidebarWidth: 320,
  appInspectorWidth: 300,
  publicLeftPanelWidth: 260,
  publicRightPanelWidth: 260,
} as const;
