// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/app" | "/app/books/[bookSlug]" | "/app/books/[bookSlug]/chapters/[chapterSlug]" | "/app/notes/[slug]" | "/books/[bookSlug]" | "/books/[bookSlug]/[chapterSlug]" | "/login" | "/notes/[slug]"
type AppRouteHandlerRoutes = "/api/auth/login" | "/api/auth/logout" | "/api/books" | "/api/books/[bookSlug]" | "/api/books/[bookSlug]/chapters" | "/api/books/[bookSlug]/chapters/[chapterSlug]" | "/api/content/tree" | "/api/execute/python" | "/api/notes" | "/api/notes/[slug]" | "/api/publish" | "/api/revisions/restore" | "/api/search" | "/api/unpublish"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/books": {}
  "/api/books/[bookSlug]": { "bookSlug": string; }
  "/api/books/[bookSlug]/chapters": { "bookSlug": string; }
  "/api/books/[bookSlug]/chapters/[chapterSlug]": { "bookSlug": string; "chapterSlug": string; }
  "/api/content/tree": {}
  "/api/execute/python": {}
  "/api/notes": {}
  "/api/notes/[slug]": { "slug": string; }
  "/api/publish": {}
  "/api/revisions/restore": {}
  "/api/search": {}
  "/api/unpublish": {}
  "/app": {}
  "/app/books/[bookSlug]": { "bookSlug": string; }
  "/app/books/[bookSlug]/chapters/[chapterSlug]": { "bookSlug": string; "chapterSlug": string; }
  "/app/notes/[slug]": { "slug": string; }
  "/books/[bookSlug]": { "bookSlug": string; }
  "/books/[bookSlug]/[chapterSlug]": { "bookSlug": string; "chapterSlug": string; }
  "/login": {}
  "/notes/[slug]": { "slug": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
