// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/app/books/[bookSlug]/chapters/[chapterSlug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/books/[bookSlug]/chapters/[chapterSlug]">> = Specific
  const handler = {} as typeof import("../../src/app/app/books/[bookSlug]/chapters/[chapterSlug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/books/[bookSlug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/books/[bookSlug]">> = Specific
  const handler = {} as typeof import("../../src/app/app/books/[bookSlug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/notes/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/notes/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/app/notes/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app">> = Specific
  const handler = {} as typeof import("../../src/app/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/books/[bookSlug]/[chapterSlug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/books/[bookSlug]/[chapterSlug]">> = Specific
  const handler = {} as typeof import("../../src/app/books/[bookSlug]/[chapterSlug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/books/[bookSlug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/books/[bookSlug]">> = Specific
  const handler = {} as typeof import("../../src/app/books/[bookSlug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/notes/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notes/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/notes/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/books/[bookSlug]/chapters/[chapterSlug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/books/[bookSlug]/chapters/[chapterSlug]">> = Specific
  const handler = {} as typeof import("../../src/app/api/books/[bookSlug]/chapters/[chapterSlug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/books/[bookSlug]/chapters/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/books/[bookSlug]/chapters">> = Specific
  const handler = {} as typeof import("../../src/app/api/books/[bookSlug]/chapters/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/books/[bookSlug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/books/[bookSlug]">> = Specific
  const handler = {} as typeof import("../../src/app/api/books/[bookSlug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/books/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/books">> = Specific
  const handler = {} as typeof import("../../src/app/api/books/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/content/tree/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/content/tree">> = Specific
  const handler = {} as typeof import("../../src/app/api/content/tree/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/execute/python/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/execute/python">> = Specific
  const handler = {} as typeof import("../../src/app/api/execute/python/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notes/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notes/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/api/notes/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notes">> = Specific
  const handler = {} as typeof import("../../src/app/api/notes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/publish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/publish">> = Specific
  const handler = {} as typeof import("../../src/app/api/publish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/revisions/restore/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/revisions/restore">> = Specific
  const handler = {} as typeof import("../../src/app/api/revisions/restore/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/unpublish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/unpublish">> = Specific
  const handler = {} as typeof import("../../src/app/api/unpublish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
